# Generated by Django 2.0 on 2020-05-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
