# Generated by Django 2.0 on 2020-05-29 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentdetails', '0002_studentdetail_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('status', models.CharField(default='PENDING', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('answer', models.CharField(max_length=1000)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentdetails.StudentDetail')),
            ],
        ),
    ]
