# Generated by Django 2.0 on 2020-05-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='answer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
