# Generated by Django 2.0 on 2020-05-22 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=200)),
                ('father_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=200)),
            ],
        ),
    ]
