# Generated by Django 2.0 on 2020-05-22 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
